import { Flame, Layers3, Shield, Sparkles } from "lucide-react";
import { ActivityFeed } from "@/components/activity-feed";
import { BreakdownBars } from "@/components/breakdown-bars";
import { OverviewStat } from "@/components/overview-stat";
import { Card } from "@/components/ui/card";
import { SectionHeading } from "@/components/ui/section-heading";
import { getProfile } from "@/lib/repository";
import { getSession } from "@/lib/session";

export default async function DashboardPage() {
  const session = getSession();
  const profile = session ? await getProfile(session.walletAddress) : null;

  return (
    <div className="space-y-10">
      <SectionHeading
        eyebrow="Dashboard"
        title="Track effort like a living on-chain resume"
        description="This view summarizes score, streak, current activity mix, and the latest verifiable submissions. Connect and sign your wallet to unlock write access."
      />

      {profile ? (
        <>
          <section className="grid gap-4 md:grid-cols-4">
            <OverviewStat label="Total score" value={`${profile.totalScore}`} detail="Accumulated across every verified effort item." />
            <OverviewStat label="Streak" value={`${profile.streak} days`} detail="Consecutive active days recorded by the scoring engine." />
            <OverviewStat label="Activities" value={`${profile.activities.length}`} detail="Submitted effort entries attached to your wallet." />
            <OverviewStat label="Wallet" value={profile.walletAddress.slice(0, 8)} detail="Authenticated wallet currently bound to this session." />
          </section>

          <section className="grid gap-4 lg:grid-cols-[0.9fr_1.1fr]">
            <Card className="space-y-5 bg-white/5">
              <div className="flex items-center gap-3 text-foreground">
                <Sparkles className="h-5 w-5 text-primary" />
                <h3 className="text-xl font-semibold">Skill breakdown</h3>
              </div>
              <BreakdownBars breakdown={profile.breakdown} />
            </Card>
            <Card className="space-y-5 bg-white/5">
              <div className="flex items-center gap-3 text-foreground">
                <Flame className="h-5 w-5 text-primary" />
                <h3 className="text-xl font-semibold">Scoring model</h3>
              </div>
              <div className="grid gap-3 text-sm leading-7 text-muted-foreground">
                <p><span className="font-semibold text-foreground">Coding:</span> weight 1.0</p>
                <p><span className="font-semibold text-foreground">Learning:</span> weight 0.7</p>
                <p><span className="font-semibold text-foreground">Watching:</span> weight 0.4</p>
                <p><span className="font-semibold text-foreground">Consistency:</span> +10% per active day streak, capped at +50%</p>
              </div>
            </Card>
          </section>

          <section className="grid gap-4 md:grid-cols-3">
            <Card className="bg-white/5">
              <Layers3 className="h-5 w-5 text-primary" />
              <h3 className="mt-5 text-lg font-semibold text-foreground">Raw activity data</h3>
              <p className="mt-3 text-sm leading-7 text-muted-foreground">Stored in a local repository adapter that mirrors the shape of a Supabase-backed MVP.</p>
            </Card>
            <Card className="bg-white/5">
              <Shield className="h-5 w-5 text-primary" />
              <h3 className="mt-5 text-lg font-semibold text-foreground">Proof storage</h3>
              <p className="mt-3 text-sm leading-7 text-muted-foreground">Uploads create deterministic proof references that behave like IPFS CIDs during development.</p>
            </Card>
            <Card className="bg-white/5">
              <Sparkles className="h-5 w-5 text-primary" />
              <h3 className="mt-5 text-lg font-semibold text-foreground">Chain recording</h3>
              <p className="mt-3 text-sm leading-7 text-muted-foreground">Each effort entry also creates a Solana-ready transaction record via a mock adapter.</p>
            </Card>
          </section>

          <section className="space-y-4">
            <SectionHeading
              eyebrow="Recent effort"
              title="Latest submissions"
              description="Every item carries a proof ref, deterministic effort hash, score, and chain record id."
            />
            <ActivityFeed activities={profile.activities.slice(0, 6)} />
          </section>
        </>
      ) : (
        <Card className="bg-white/5 p-8">
          <h3 className="text-2xl font-semibold text-foreground">Authenticate your wallet first</h3>
          <p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">
            Connect Phantom, sign the login message, then come back here. The dashboard reads the session cookie generated by the backend.
          </p>
        </Card>
      )}
    </div>
  );
}
